### ISSUE TITLE
Cannot run `setup_user.sh`

### ISSUE THREAD

**Issue by kevinschweikert** [avorus-soft/avorus#6]
I got the installer to run until the user setup and it fails with this error message:

```shell
Do you want to run ./install/setup_user.sh interactively? (y/n): y
WARN[0000] /Users/kevinschweikert/projects/imen/avorus/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it t
o avoid potential confusion 
[+] Creating 2/0
 ✔ Container avorus-db      Created                                                                                                              0.1s 
 ✔ Container avorus-broker  Created                                                                                                              0.1s 
[+] Running 2/0
 ✔ Container avorus-broker  Started                                                                                                              0.1s 
 ✔ Container avorus-db      Started                                                                                                              0.1s 
Creating system user...
No servers found yet, Timeout: 30s, Topology Description: <TopologyDescription id: 6756f390db17120b4212b190, topology_type: Unknown, servers: [<Server
Description ('kevin-macbook-pro-work.local', 27017) server_type: Unknown, rtt: None>]>
Please create your admin account
Email: admin@im-en.com
Password (can be changed later): 
Verify password: 
Traceback (most recent call last):
  File "/api/init_user.py", line 64, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/api/init_user.py", line 59, in main
    await create_user(username, password, is_superuser=True)
  File "/api/init_user.py", line 21, in create_user
    await init_beanie(
  File "/usr/local/lib/python3.11/site-packages/beanie/odm/utils/init.py", line 782, in init_beanie
    await Initializer(
  File "/usr/local/lib/python3.11/site-packages/beanie/odm/utils/init.py", line 134, in __await__
    yield from self.init_class(model).__await__()
  File "/usr/local/lib/python3.11/site-packages/beanie/odm/utils/init.py", line 745, in init_class
    await self.init_document(cls)
  File "/usr/local/lib/python3.11/site-packages/beanie/odm/utils/init.py", line 577, in init_document
    build_info = await self.database.command({"buildInfo": 1})
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/_csot.py", line 120, in csot_wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/database.py", line 906, in command
    with self._client._conn_for_reads(read_preference, session, operation=command_name) as (
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1683, in _conn_from_server
    with self._checkout(server, session) as conn:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/mongo_client.py", line 1593, in _checkout
    with server.checkout(handler=err_handler) as conn:
  File "/usr/local/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/pool.py", line 1336, in checkout
    conn = self._get_conn(checkout_started_time, handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/pool.py", line 1495, in _get_conn
    conn = self.connect(handler=handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/pool.py", line 1296, in connect
    conn.authenticate()
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/pool.py", line 648, in authenticate
    auth.authenticate(creds, self, reauthenticate=reauthenticate)
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/auth.py", line 452, in authenticate
    auth_func(credentials, conn)
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/auth.py", line 356, in _authenticate_default
    return _authenticate_scram(credentials, conn, "SCRAM-SHA-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/auth.py", line 95, in _authenticate_scram
    res = conn.command(source, cmd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/helpers.py", line 45, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/pool.py", line 538, in command
    return command(
           ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymongo/synchronous/network.py", line 218, in command
    helpers_shared._check_command_response(
  File "/usr/local/lib/python3.11/site-packages/pymongo/helpers_shared.py", line 247, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: Authentication failed., full error: {'ok': 0.0, 'errmsg': 'Authentication failed.', 'code': 18, 'codeName': 'Authenti
cationFailed'}
./install/setup_user.sh failed. Exiting the installation.
```

Could there be some issues with the certificates?

**Comment by worosom** [comment]
The `setup_user.sh` script is designed to be run during the initial setup, to create the first superuser.
Subsequent users have to be created via the UI or REST API, authenticated by an existing superuser.

**Comment by worosom** [comment]
Just making sure @kevinschweikert if that's

**Comment by worosom** [comment]
@kevinschweikert I couldn't reproduce the issue.
If you can provide steps for reproduction that would be appreciated.
